# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '8.x' # replace this value with the version that you need for your project
- script: |
    sudo npm install --global sfdx-cli
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  env:
    JWT_KEY: $(sfdx.jwt.auth.key)
